### ISSUE TITLE
No module named solver

### ISSUE THREAD

**Issue by gbnci** [CMUSchwartzLab/TUSV-ext#1]
Good afternoon:
I am trying to get this software to work for me using downloaded testing dataset from your site but failed so far. First of all, I could access Gurobi license and using module load Gurobi into my working environment. Also I used conda to access python (version 2.7). Here are some of the code I used:

conda create --name tusv python=2.7 bioconda::ete2 graphviz biopython sympy
conda activate tusv;
pip install graphviz
python -V 
python /data/wangyong/Tusv_ext/tusv-ext.py -i /data/wangyong/Tusv_ext/testing/vcf -o /data/wangyong/Tusv_ext/testing/result/ -n 5 -c 50 -t 10 -r 10 -col 1 -leaf 1 -sv_ub 5 -const 50;
conda deactivate;

The error I got after I ran the above code is:
Traceback (most recent call last):
  File "/data/wangyong/Tusv_ext/tusv-ext.py", line 23, in <module>
    import solver as sv
ImportError: No module named solver

Could you please give me some suggestions to take care of this error? Thanks.
By the way, another question I have is about the genome I can apply this software to. Specifically, whether I can use this software on species like mouse, dog et al other than human?
Thanks for your help.
YH

**Comment by cindyfu** [comment]
Hi, I think in order to make it work you might need to run tusv-ext under the directory and directly run 

> python tusv-ext.py

Otherwise you might need to change line 21 22 in tusv-ext.py to adjust the path to the full path instead of the relative path.

And to your second question, yes I would say that you could potentially use that to any species as long as it is bulk sequencing for heterogeneous tumor.

Let me know if you have further question or problem.

**Comment by gbnci** [comment]
Hi, Cindy: Thanks for your suggestions. With the help from our IT stuff, I think I have got through the "solver" error, but still got another similar one as shown below:
Traceback (most recent call last):
  File "tusv-ext.py", line 24, in <module>
    import file_manager as fm      # sanitizes file and directory arguments
ImportError: No module named file_manager

I also try to run with "python tusv-ext.py ...", still got the same error above. any suggestions? Because I am kind of new to python, not quite sure how to change line 21 and 22. For instance, if conda path is at /data/conda/envs/tusv/bin, and I can put tusv-ext.py at my working directory. Can you give me a suggestion about how to change the command lines here?
Thanks
YH

**Comment by cindyfu** [comment]
I think it should be the similar issue. Can you send an email to xuecongf@andrew.cmu.edu and we can discuss more detail?
